kind: Pod
apiVersion: v1
metadata:
  name: pgadmin4
spec:
  containers:
    - name: pgadmin4
      image: dpage/pgadmin4
      env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: "admin"
      - name: PGADMIN_DEFAULT_PASSWORD
        value: "admin"
      ports:
        - containerPort: 80
          hostPort: 8080
