kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: go-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: go-api/go-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          hostPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: api